name: CI

on:
  pull_request:
    branches: [master]

jobs:
  run_tests_type_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - uses: ./.github/actions/ci-common-setup-locally-packaged

      - name: Type-check tests code
        run: pnpm run test-typings-check
