name: CI

on:
  pull_request:
    branches: [master]

jobs:
  lint_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - uses: ./.github/actions/ci-common-setup

      - name: Lint check
        run: pnpm exec eslint --cache

  prettier_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - uses: ./.github/actions/ci-common-setup

      - name: Prettier check
        run: pnpm exec prettier --check "./{src,spec}/**/*.{ts,tsx,js,mjs,jsx}"

  ts_build_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - uses: ./.github/actions/ci-common-setup

      - name: TypeScript test build
        run: pnpm run build-check

  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - uses: ./.github/actions/ci-common-setup-locally-packaged

      - name: Run tests against packaged library code
        run: |
          pnpm test

  run_type_check_on_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - uses: ./.github/actions/ci-common-setup-locally-packaged

      - name: Type-check tests code
        run: |
          pnpm run test-typings-check
